# Generated by Django 5.1.6 on 2025-03-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundryadmin', '0008_alter_price_bottomwear_alter_price_topwear_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='bedbath',
            field=models.IntegerField(default='25'),
        ),
    ]
