# Generated by Django 5.1.6 on 2025-03-06 03:09

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0034_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_image', models.ImageField(default='default-profile.jpg', upload_to='profile_pics/')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='userreqeuest',
            name='payment',
            field=models.CharField(choices=[('Unpaid', 'Não pago'), ('Cash', 'Dinheiro'), ('Online', 'Cartão')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userreqeuest',
            name='progress',
            field=models.CharField(choices=[('Pending', 'Pendente'), ('Accept', 'Aceito'), ('Inprogress', 'Andamento'), ('Finish', 'Finalizado'), ('Cancle', 'Cancelado')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userreqeuest',
            name='service_type',
            field=models.CharField(choices=[('drop', 'Retirar'), ('pickup', 'House Pickup')], max_length=10),
        ),
    ]
