# Generated by Django 5.1.6 on 2025-03-06 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_customuser_alter_userreqeuest_payment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
